version: '3'
services:
  grafana:
    image: grafana/grafana:10.2.3
    restart: always
    network_mode: host
    # ports:
    #   - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana/
      # - ./defaults.ini:/usr/share/grafana/conf/defaults.ini:ro
