version: '3'
services:
  nginx:
    image: xqada2017/nginx:1.25.3-geoip2
    # restart: on-failure:3
    restart: always
    network_mode: host
    # ports:
    #   - 80:80
    #   - 443:443
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/stream.d:/etc/nginx/stream.d
      - ./geoip2db:/etc/geoip2db
      - ./www:/www
