version: '3'
services:
  cadvisor:
    image: xqada2017/cadvisor:v0.47.2
    # image: gcr.io/cadvisor/cadvisor:v0.47.2
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
    ports:
      - 8180:8080
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
